### ISSUE TITLE
Issue while executing flow, pasted log

### ISSUE THREAD

**Issue by NitinKeshavB** [EmilRex/kubernetes-worker-demo#2]
```
Worker 'KubernetesWorker adff9a6f-a63f-4aa8-b54e-5edea93413d5' submitting flow run 'a36e4145-453d-4a5c-8e52-5645b91c9210'
08:23:49 PM
prefect.flow_runs.worker
Creating Kubernetes job...
08:23:51 PM
prefect.flow_runs.worker
Job 'gifted-spaniel-csxrs': Pod has status 'Pending'.
08:23:51 PM
prefect.flow_runs.worker
Completed submission of flow run 'a36e4145-453d-4a5c-8e52-5645b91c9210'
08:23:52 PM
prefect.flow_runs.worker
Job 'gifted-spaniel-csxrs': Pod has status 'Running'.
08:23:53 PM
prefect.flow_runs.worker
Flow could not be retrieved from deployment.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/prefect/deployments/steps/core.py", line 122, in run_steps
    step_output = await run_step(step, upstream_outputs)
  File "/usr/local/lib/python3.9/site-packages/prefect/deployments/steps/core.py", line 93, in run_step
    result = await from_async.call_soon_in_new_thread(
  File "/usr/local/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 292, in aresult
    return await asyncio.wrap_future(self.future)
  File "/usr/local/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 316, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/prefect/deployments/steps/pull.py", line 27, in set_working_directory
    os.chdir(directory)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/prefect/kubernetes-worker-demo'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 395, in retrieve_flow_then_begin_flow_run
    flow = await load_flow_from_flow_run(flow_run, client=client)
  File "/usr/local/lib/python3.9/site-packages/prefect/client/utilities.py", line 51, in with_injected_client
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/prefect/deployments/deployments.py", line 203, in load_flow_from_flow_run
    output = await run_steps(deployment.pull_steps)
  File "/usr/local/lib/python3.9/site-packages/prefect/deployments/steps/core.py", line 150, in run_steps
    raise StepExecutionError(f"Encountered error while running {fqn}") from exc
prefect.deployments.steps.core.StepExecutionError: Encountered error while running prefect.projects.steps.set_working_directory
```

**Comment by EmilRex** [comment]
@NitinKeshavB Thanks for reporting! What's the output you get when running the following command: `prefect version`?

**Comment by NitinKeshavB** [comment]
no problem, I want this to work :(
here we go with version

```
Version:             2.10.17+22.g9ff7582fb
API version:         0.8.4
Python version:      3.9.16
Git commit:          9ff7582f
Built:               Tue, Jun 27, 2023 4:07 PM
OS/Arch:             win32/AMD64
Profile:             default
Server type:         cloud
```

**Comment by NitinKeshavB** [comment]
I was able to fix this in new prefect version.

Issue said cannot find folder - /opt/prefect/kubernetes-worker-demo that is set in prefect.yaml. By looking at dockerfile it was clear that the project folder - kubernetes-worker-demo is not created but it creates /opt/prefect/prefect-worker/

earlier prefect version doesn't fail the deployment when something critical like this is in code.

In New prefect version deployment fails if something like above is missing.  Leaving the dockerfile to be validated further helping me to debug this issue.

Fix was to change the folder name to  /opt/prefect/prefect-worker/ in prefect.yaml

working version
Version:             2.10.18
API version:         0.8.4
Python version:      3.9.16
Git commit:          cf177852
Built:               Thu, Jun 29, 2023 2:34 PM
OS/Arch:             win32/AMD64
Profile:             default
Server type:         cloud
